#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
DEV_DIR="$REPO_ROOT/dev"
ENV_FILE="$DEV_DIR/.env.local-full"

if ! command -v docker >/dev/null 2>&1; then
  echo "ERROR: docker was not found." >&2
  exit 1
fi

if ! docker info >/dev/null 2>&1; then
  echo "ERROR: Docker Desktop is not running or is not available from this shell." >&2
  exit 1
fi

if ! command -v node >/dev/null 2>&1; then
  echo "ERROR: Node.js is required to generate local VAPID keys." >&2
  exit 1
fi

HOST_IP="$(docker run --rm --add-host=host.docker.internal:host-gateway alpine:3.20 \
  sh -lc "getent hosts host.docker.internal | awk 'NR==1 {print \$1}'" 2>/dev/null || true)"

if [[ -z "$HOST_IP" ]]; then
  echo "ERROR: could not resolve host.docker.internal from a container." >&2
  exit 1
fi

PUSH_PUBLIC_KEY=""
PUSH_PRIVATE_KEY=""
PUSH_SUBJECT="mailto:test@huly.local"

if [[ -f "$ENV_FILE" ]]; then
  PUSH_PUBLIC_KEY="$(sed -n 's/^PUSH_PUBLIC_KEY=//p' "$ENV_FILE" | head -n1)"
  PUSH_PRIVATE_KEY="$(sed -n 's/^PUSH_PRIVATE_KEY=//p' "$ENV_FILE" | head -n1)"
  PUSH_SUBJECT="$(sed -n 's/^PUSH_SUBJECT=//p' "$ENV_FILE" | head -n1)"
  PUSH_SUBJECT="${PUSH_SUBJECT:-mailto:test@huly.local}"
fi

if [[ -z "$PUSH_PUBLIC_KEY" || -z "$PUSH_PRIVATE_KEY" ]]; then
  read -r PUSH_PUBLIC_KEY PUSH_PRIVATE_KEY < <(node <<'NODE'
const { generateKeyPairSync } = require('node:crypto')
const { privateKey } = generateKeyPairSync('ec', { namedCurve: 'prime256v1' })
const jwk = privateKey.export({ format: 'jwk' })
const publicBytes = Buffer.concat([
  Buffer.from([4]),
  Buffer.from(jwk.x, 'base64url'),
  Buffer.from(jwk.y, 'base64url')
])
process.stdout.write(`${publicBytes.toString('base64url')} ${jwk.d}\n`)
NODE
  )
fi

cat > "$ENV_FILE" <<ENV
# Generated by scripts/local-full/prepare-env.sh.
LIVEKIT_NODE_IP=$HOST_IP
LIVEKIT_SERVER_IMAGE=livekit/livekit-server:v1.12.0
LIVEKIT_EGRESS_IMAGE=livekit/egress:v1.12.0
PUSH_PUBLIC_KEY=$PUSH_PUBLIC_KEY
PUSH_PRIVATE_KEY=$PUSH_PRIVATE_KEY
PUSH_SUBJECT=$PUSH_SUBJECT
ENV

chmod 600 "$ENV_FILE"
printf 'Created %s\n' "$ENV_FILE"
printf 'LIVEKIT_NODE_IP=%s\n' "$HOST_IP"
printf 'PUSH_PUBLIC_KEY=%s...\n' "${PUSH_PUBLIC_KEY:0:16}"
